diarios={
0: {'diario':'Xataka',
'seccion':'Tecnología',
'rss': 'https://www.xataka.com/tag/tecnologia/rss2.xml'},
1: {'diario':'Xataka',
'seccion':'Ciencia',
'rss': 'https://www.xataka.com/tag/ciencia/rss2.xml'},
2: {'diario':'Xataka',
'seccion':'Internet',
'rss': 'https://www.xataka.com/tag/internet/rss2.xml'},
3: {'diario':'Xataka',
'seccion':'Videojuegos',
'rss': 'https://www.xataka.com/tag/videojuegos/rss2.xml'},
4: {'diario':'Gizmodo',
'seccion':'Tecnología',
'rss': 'https://es.gizmodo.com/tag/tecnologia/rss'},
5: {'diario':'Gizmodo',
'seccion':'Ciencia',
'rss': 'https://es.gizmodo.com/tag/ciencia/rss'},
6: {'diario':'Gizmodo',
'seccion':'Internet',
'rss': 'https://es.gizmodo.com/tag/internet/rss'},
7: {'diario':'Gizmodo',
'seccion':'Videojuegos',
'rss': 'https://es.gizmodo.com/tag/videojuegos/rss'}
}
